import {z} from 'zod/v4';
import type mongoose from 'mongoose';
import {unwrapZodSchema} from './zod-helpers.js';

/** Remove only fields generated by Mongoose that the corresponding Zod object did not declare. */
export function prepareForZodValidation(
  schema: z.ZodTypeAny,
  value: any,
  mongooseSchema?: mongoose.Schema,
  pathPrefix = '',
): any {
  if (value === null || value === undefined) return value;

  const {schema: unwrapped} = unwrapZodSchema(schema);
  const def = (unwrapped as any)?._def;

  if (def?.type === 'lazy') {
    return prepareForZodValidation(def.getter(), value, mongooseSchema, pathPrefix);
  }

  if (def?.type === 'object' && typeof value === 'object' && !Array.isArray(value)) {
    const {shape} = unwrapped as z.ZodObject<any>;
    const result = {...value};
    if (mongooseSchema && !pathPrefix && mongooseSchema.options._id !== false && !Object.hasOwn(shape, '_id')) {
      delete result._id;
    }
    const versionKey = !pathPrefix && mongooseSchema?.options.versionKey;
    if (typeof versionKey === 'string' && !Object.hasOwn(shape, versionKey)) {
      delete result[versionKey];
    }
    const timestamps = !pathPrefix && mongooseSchema?.options.timestamps;
    if (timestamps) {
      for (const key of ['createdAt', 'updatedAt'] as const) {
        const configured = typeof timestamps === 'object' ? timestamps[key] : undefined;
        if (configured === false) continue;
        const fieldName = typeof configured === 'string' ? configured : key;
        if (!Object.hasOwn(shape, fieldName)) delete result[fieldName];
      }
    }

    for (const [key, fieldSchema] of Object.entries(shape)) {
      if (!Object.hasOwn(result, key)) continue;
      const path = pathPrefix ? `${pathPrefix}.${key}` : key;
      const nestedSchema = (mongooseSchema?.path(path) as any)?.schema;
      result[key] = prepareForZodValidation(
        fieldSchema as z.ZodTypeAny,
        result[key],
        nestedSchema || mongooseSchema,
        nestedSchema ? '' : path,
      );
    }
    return result;
  }

  if (Array.isArray(value)) {
    if (def?.type === 'array' || def?.type === 'set') {
      const element = (unwrapped as any).element || def.valueType;
      return element
        ? value.map((item) => prepareForZodValidation(element, item, mongooseSchema, pathPrefix))
        : value;
    }
    if (def?.type === 'tuple') {
      return value.map((item, index) => {
        const element = def.items?.[index] || def.rest;
        return element ? prepareForZodValidation(element, item, mongooseSchema, pathPrefix) : item;
      });
    }
  }

  return value;
}
